version: '3.4'

services:
  nosqldata:
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ${HOST_VOLUMES_PATH}/mongo:/data/db
        
  seq:
    container_name: "seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - ${HOST_VOLUMES_PATH}/seq:/data

  definition-api:
    container_name: "definition-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"