version: '3.4'

services:
  nosqldata:
    image: mongo
    
  seq:
    image: datalust/seq:latest
    
  definition-api:
    image: ${DOCKER_REGISTRY-}definition.api
    build:
      context: .
      dockerfile: src/Services/Definition/Definition.Api/Dockerfile
    depends_on:
      - nosqldata
      - seq